name: IHS Stop Action
description: 'Action to stop IBM HTTP Server (IHS) for a given application, OC, environment, and site.'
inputs:
  application:
    description: 'Application name for stopping IHS'
    required: true
  environment:
    description: 'Environment to stop IHS'
    required: true
  site:
    description: 'Site to stop IHS'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Stop IHS'
      shell: bash
      run: |
        echo "Stopping IHS for application: ${{ inputs.application }}, OC: ${{ inputs.oc }}, Environment: ${{ inputs.environment }}, Site: ${{ inputs.site }}"  
        echo "::notice::Stopping IHS for application: ${{ inputs.application }}, OC: ${{ inputs.oc }}, Environment: ${{ inputs.environment }}, Site: ${{ inputs.site }}"      
        